theme: jekyll-theme-slate
title: Kevin's Site
description: More to come soon...
permalink: pretty
repository: jkmills78/jkmills78.github.io
github: [metadata]
encoding: UTF-8
kramdown:
  input: GFM
  hard_wrap: false
collections:
  code_examples:
    output: true
profiles:
  github: https://github.com/jkmills78
  linkedin: https://www.linkedin.com/in/kevinmills78/
  stackoverflow: https://stackoverflow.com/users/1306571/kevin-mills
  csslp: https://www.youracclaim.com/badges/2a5db860-fdbb-4aff-bbb7-8ab498f56aeb/public_url